"""添加一张博客表

Revision ID: fe203c008001
Revises: 
Create Date: 2019-03-04 16:14:48.143109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe203c008001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('small_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_user_id', sa.Integer(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('picure_content', sa.String(length=900), nullable=True),
    sa.ForeignKeyConstraint(['post_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_small_blog_title'), 'small_blog', ['title'], unique=False)
    op.drop_index('user_head_picture_idx', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_head_picture_idx', 'user', ['head_picture'], unique=False)
    op.drop_index(op.f('ix_small_blog_title'), table_name='small_blog')
    op.drop_table('small_blog')
    # ### end Alembic commands ###
